export const EMAIL_FIELD = 'email'
export const PASS_FIELD = 'password'
export const CODE_FIELD = 'code'
export const CODE_FIELD_PLACEHOLDER = 'Code has sent to the email'
export const NAME_FIELD = 'name'
